services:
  php:
    build:
      context: ./php84
    container_name: php84
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - mongodb

  web:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    ports: 
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: mysql80
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: intranet
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: intranet
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  dbdata:
  mongodbdata: